django_form/django_form/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django_app.views import *
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'django_form.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/$',index),
    url(r'^text/modelsform/$',create_pro,name='create'),
    url(r'^text/update/$',update,name='update'),

)
urlpatterns += patterns('',
    url(r'^text/careate_book/$',createBook,name='create'),
    url(r'^text/find_book/$',findAll,name='findall'),
    url(r'^text/(?P<id>\w)/update/$',updateBook,name='update'),
    url(r'^text/update_book/$',updateBooSuc,name='update_success'),
)
#login user
urlpatterns += patterns('',
     # url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
     url(r'^login/$',login_view),
     url(r'^logout/$',logout_view),
)

django_form/django_app/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import User,AbstractUser,AbstractBaseUser,PermissionsMixin,BaseUserManager
from django.utils import  timezone


# Create your models here.

# class UserManager(BaseUserManager):
#
#     use_in_migrations=True
#     def _create_user(self, email, password,is_supperuser,**extra_fields):
#         """
#         Creates and saves a User with the given username, email and password.
#         """
#         now = timezone.now()
#         if not email:
#             raise ValueError('The given username must be set')
#         email = self.normalize_email(email)
#         user = self.model(email=email,is_active=True,
#                             is_supperuser=is_supperuser,
#                             last_login=now,
#                             **extra_fields)
#         user.set_password(password)
#         user.save(using=self._db)
#         return user
#
#     def create_user(self, email=None, password=None, **extra_fields):
#         return self._create_user(email,password, False, **extra_fields)
#
#     def create_superuser(self, username, email, password, **extra_fields):
#         return self._create_user(username, email, password,  True,
#                                  **extra_fields)
#
class MyUser(AbstractUser):
    address = models.CharField(max_length=30)




# class Profile(models.Model):
#     user = models.OneToOneField(User)
#
#     blog = models.CharField(max_length=128,blank=True)
#     location = models.CharField(max_length=128,blank=True)
#     occupation= models.CharField(max_length=128,blank=True)
#
#     reward = models.IntegerField(default=0,blank=True)
#     topic_count = models.IntegerField(default=0,blank=True)
#     post_count = models.IntegerField(default=0,blank=True)
#
#     class Admin:
#         list_display = ('user', 'blog', 'location', 'occupation', 'reward', 'topic_count', 'post_count')



class Product(models.Model):
    title = models.CharField(max_length=30,verbose_name='标题')
    description = models.TextField(verbose_name='描述')
    photo = models.ImageField(verbose_name='图片')
    price = models.FloatField(verbose_name='价格')

    def __unicode__(self):
        return self.title


class Author(models.Model):
    name = models.CharField(max_length=30,verbose_name='作者姓名')
    age = models.IntegerField(verbose_name='年龄')
    address= models.CharField(max_length=30,verbose_name='地址')
    # class Meta:
    #     db_table='verbose_name'

    def __unicode__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=30,verbose_name='作者书名')
    price = models.FloatField(verbose_name='价格')
    authors = models.ManyToManyField(Author)
    # models.OneToOneField

    def __unicode__(self):
        return self.title

django_form/django_app/forms.py
#coding:utf-8
from django import forms
from django_app.models import *
from django.conf import settings

#引用富文本编辑器
class Kindeditoe(forms.Textarea):
    class Media:
        js = (settings)

class LoginFrom(forms.Form):
    username = forms.CharField(label='用户名称')
    password = forms.CharField(label='用户密码', widget=forms.PasswordInput())
    class Meta:
        pass

class ProductForm(forms.ModelForm):

    # title = forms.CharField(max_length=30)
    # description = forms.Textarea()
    # photo = forms.ImageField()
    # price = forms.FloatField()

    class Meta:
        model = Product
        fields =['title','description','photo','price']

class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ['title','price','authors']

django_form/django_app/views.py
#coding:utf-8
from django.shortcuts import render,render_to_response,HttpResponseRedirect,HttpResponse
from django_app import forms
from django_app.models import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# Create your views here.


def login_view(req):
    # if req.user.is_authenticated():
            # 方法一
            # form = LoginFrom(req.POST or None,req.FILES)
            # if form.is_valid():
            #     username = form.cleaned_data['username']
            #     password = form.cleaned_data['password']
            #方法二
    if req.method=='POST':
            username=req.POST.get('username','')
            password=req.POST.get('password','')
            # if username and password:
            #     user=User.objects.get(username__icontains=username,password__excat=password)
            user = authenticate(username=username,password=password)
            if user is not None:
                # login(re)
                login(req,user)
                return render_to_response('index.html', locals())
    # else:
    #     return HttpResponseRedirect('/login/?next=%s' % req.path)
    else:
        form=forms.LoginFrom()
        return render_to_response('login.html',locals())


def logout_view(req):
    logout(req)
    return HttpResponseRedirect('/login/')


def index(req):#login
    return render_to_response('depot/create_pro.html')

def create_pro(req):
    form=forms.ProductForm()
    if req.method == 'POST':
        form =forms.ProductForm(req.POST or None , req.FILES)
        if form.is_valid():
            form.save()
    return render(req , 'depot/create_pro.html', locals())
def create_view(req):
    req.POST.get('name' , '')


def update(req):#update
    form=forms.ProductForm(instance=Product.objects.get(pk=1))
    # form.save()
    # udate this form
    return render_to_response('depot/find_pro.html',locals())

def createBook(req):# create book
    form = forms.BookForm()
    if req.method == 'POST':
        form = forms.BookForm(req.POST or None, req.FILES)
        if form.is_valid():
            form.save()
    return render(req,'book/create_book.html',locals())

def findAll(req): # find all this
    books = Book.objects.all()
    return render_to_response('book/find_book.html',locals())

def updateBook(req,id): # id find this
    if req.method == 'POST':
        form = forms.BookForm(req.POST,instance=Book.objects.get(id=id))
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/text/find_book/')
    else:
        form = forms.BookForm(instance=Book.objects.get(id=id))
        return render_to_response('book/update_book.html',locals())


def updateBooSuc(req):  # update success
    if req.method == 'POST':
        form = forms.BookForm(req.POST)
        if form.is_valid():
            new_blog=form.save(commit=False)
            new_blog.authors = form.cleaned_data['authors']
            new_blog.save()
            form.save_m2m()
    return render_to_response('depot/success.html',locals())

django_form/templates/depot/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>增删改</title>
</head>
<body>
  {% block create_pro %}
  {% endblock %}
  {% block update_pro %}
  {% endblock %}
  {% block create_book %}
  {% endblock %}
  {% block findbooks %}
  {% endblock %}
  {% block updatebook %}
  {% endblock %}
  {% block login  %}
  {% endblock %}
</body>
</html>

django_form/templates/depot/create_pro.html
{% extends 'depot/base.html' %}
{% block title %}测试ModelForm{% endblock %}
{% block create_pro %}
    <form method="post" action="/text/modelsform/">{% csrf_token %}
        <table>
            <tr><td><lable for='id_title'>标题:</lable></td><td>{{ form.title }}</td><td>{{ form.title.errors }}</td></tr>
            <tr><td><lable for='id_description'>描述:</lable></td><td>{{ form.description }}</td><td>{{ form.description.errors }}</td></tr>
            <tr><td><lable for='id_photo'>图片文件:</lable></td><td>{{ form.photo }}</td><td>{{ form.photo.errors }}</td></tr>
            <tr><td><lable for='id_price'>价格:</lable></td><td>{{ form.price }}</td><td>{{ form.price.errors }}</td></tr>
            <tr><td><input type="submit" value="注册" /></td><td><input type="reset" value="重置"/></td><td></td></tr>
        </table>
    </form>
{% endblock %}

django_form/templates/depot/find_pro.html
{% extends 'depot/base.html' %}
{% block title %}测试ModelForm{% endblock %}
{% block create_pro %}
    <form method="post" action="/text/modelsform/">{% csrf_token %}
        <table>
            <tr><td><lable for='id_title'>标题:</lable></td><td>{{ form.title }}</td><td>{{ form.title.errors }}</td></tr>
            <tr><td><lable for='id_description'>作者名:</lable></td><td>{{ form.description }}</td><td>{{ form.description.errors }}</td></tr>
            <tr><td><lable for='id_photo'>出生日期:</lable></td><td>{{ form.photo }}</td><td>{{ form.photo.errors }}</td></tr>
            <tr><td><lable for='id_price'>价格:</lable></td><td>{{ form.price }}</td><td>{{ form.price.errors }}</td></tr>
            <tr><td><input type="submit" value="注册" /></td><td><input type="reset" value="重置"/></td><td></td></tr>
        </table>
    </form>
{% endblock %}

django_form/templates/depot/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
   <h1>成功</h1>
</body>
</html>