search_pro/search_pro/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from search.views import *

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'search_pro.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/$',index,name='index'),
    url(r'^search/$',search,name='search'),
    url(r'^ques/$',questionDetail,name='ques'),
    url(r'^ques/(?P<cid>\w+)/comm/(?P<qid>\w+)/$',quesComm),
)

search_pro/search/models.py
# -*- coding:utf-8 -*-
from django.db import models
from django import forms
# Create your models here.
class Word(models.Model):
    # id
    word_value = models.CharField(max_length=30, verbose_name='词语内容')
    class Meta:
        verbose_name = '词语'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.word_value

# class quesForm(forms.ModelForm):
#     class Meta:
#         models=Question
#         fields=['__all__']


class Question(models.Model):
    title = models.CharField('标题', max_length=150)
    body = models.TextField('问题内容')
    created = models.DateTimeField('创建时间', auto_now_add=True)
    modified = models.DateTimeField('修改时间', auto_now=True)
    def __unicode__(self):
        return self.title
    class Meta:
        verbose_name = '问题'
        verbose_name_plural = '问题'
        ordering = ['-created']
class Answer(models.Model):
    body = models.TextField('答案内容')
    created = models.DateTimeField('创建时间', auto_now_add=True)
    modified = models.DateTimeField('修改时间', auto_now=True)
    count = models.IntegerField('计数', default=0,null=True)
    question = models.ForeignKey(Question, blank=True, null=True, verbose_name='问题')
    def __unicode__(self):
        return self.body
    class Meta:
        verbose_name = '答案'
        verbose_name_plural = '答案'
        ordering = ['-created']
class Comment(models.Model):
    body = models.CharField('评论内容', max_length=500)
    question = models.ForeignKey(Question, blank=True, null=True, verbose_name='问题')
    answer = models.ForeignKey(Answer, blank=True, null=True, verbose_name='答案')
    def __unicode__(self):
        return self.body

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = '评论'

search_pro/search/views.py
from django.shortcuts import render,render_to_response,HttpResponse,HttpResponseRedirect
from search.models import *
from django.core.serializers import serialize
import json
from django.core.paginator import Paginator


# Create your views here.

def index(req):
    return render_to_response('index.html')

def search(req):
    word = req.GET.get('word','')
    print word
    if word:
        pa =Paginator(Word.objects.filter(word_value__contains=word),3)
        # list= Word.objects.filter(word_value__contains=word)[:4]#exact
        word_list=serialize('json',pa.page(1))
    return HttpResponse(json.dumps(word_list),content_type='application/json')

def questionDetail(req):
    ques=Question.objects.get(id=1)
    return render_to_response('question_detail.html',locals())

def quesComm(req,cid,qid):
    print cid,qid
    Comment.objects.get(id=cid).delete()
    return HttpResponseRedirect('/ques/')

search_pro/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link href ="{% static 'css/index.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
</head>
<body>
    <div style="margin: 0 auto">
        请输入
        <input type="text" name="word" id="word" onkeyup="do_ajax()">
        <span id="word_info">&nbsp;</span>
        {% comment %}<input type="submit" id="submit" value="搜索" src="" onclick="drop_up()">{% endcomment %}
        <div id="drop_down">
            <ul class="list"  name="word_txt" id="word_txt">

            </ul>
        </div>
    </div>
</body>
</html>

search_pro/templates/question_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <div>
         <h2>{{ ques.title }}</h2><br/>
         <span>{{ ques.body }}</span><br/>
         <span>答案</span><br/>
          {% for ans in ques.answer_set.all %}
              <span>{{ ans.id }}</span><br/>
          {% endfor %}
         <h3>评论</h3>
         {% for conn in ques.comment_set.all %}
          <span>{{ conn.id }}</span>
         {% endfor %}
    </div>
</body>
</html>